version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:11.10.1
    steps:
      - checkout
      - run: npm install

  lint:
    docker:
      - image: circleci/node:11.10.1
    steps:
      - checkout
      - run: npm install
      - run: npm lint

  # test:
  #   docker:
  #     - image: circleci/node:11.10.1
  #   steps:
  #     - checkout
  #     - run: yarn install
  #     - run: yarn test:unit

  deploy:
    docker:
      - image: circleci/node:11:10:1
    steps:
      - checkout
      - run: npm install
      - run: npm firebase deploy --token "$FIREBASE_TOKEN" --only hosting

workflows:
  version: 2
  integration:
    jobs:
      - build
      - lint
      # - test
    - deploy:
        requires:
          - build
          - lint
          # - test
        filters:
          branches:
            only: master