version: 2.1

commands:
  checkout_and_restore_cache:
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}

executors:
  node:
    docker:
      - image: circleci/node:11.10.1

jobs:
  install:
    executor: node
    steps:
      - checkout_and_restore_cache
      - run: npm install
      - save_cache:
        key: v1-dependencies-{{ checksum "package-lock.json" }}
        paths:
          - ./node_modules
  lint:
    docker:
      - image: circleci/node:11.10.1
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm lint

  # test:
  #   docker:
  #     - image: circleci/node:11.10.1
  #   steps:
  #     - checkout
  #     - run: yarn install
  #     - run: yarn test:unit

  deploy:
    docker:
      - image: circleci/node:11:10:1
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm firebase deploy --token "$FIREBASE_TOKEN" --only hosting

workflows:
  version: 2
  integration:
    jobs:
      - install
      - lint:
        requires:
          - install
    - deploy:
        requires:
          - lint
          # - test
        filters:
          branches:
            only: master